---
  - include_tasks: create_project.yml
  - include_tasks: create_vpc.yml
  - include_tasks: create_vpc_tier.yml
  - include_tasks: create_vm_template.yml
  - include_tasks: create_certificates.yml
  - include_tasks: create_token.yml
  - include_tasks: create_vm.yml
  - include_tasks: create_inv.yml
  - include_tasks: create_portforward.yml
